# Generated by Django 5.2.8 on 2025-12-01 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatsession",
            options={"ordering": ["-last_activity"]},
        ),
        migrations.AddField(
            model_name="chatsession",
            name="title",
            field=models.CharField(
                default="New Chat",
                help_text="User-given title for the chat session.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sources",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of citation sources from grounding.",
            ),
        ),
    ]
