# Generated by Django 5.2.8 on 2025-12-03 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_chatsession_options_chatsession_title_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RateLimitConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "messages_per_hour",
                    models.IntegerField(default=30, help_text="Max messages per hour"),
                ),
                (
                    "messages_per_day",
                    models.IntegerField(default=200, help_text="Max messages per day"),
                ),
                (
                    "api_calls_per_minute",
                    models.IntegerField(
                        default=5, help_text="Max API calls per minute"
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(
                        default=False, help_text="Is this a premium user?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_limit_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="APIUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        help_text="API endpoint called (e.g., 'chat', 'search')",
                        max_length=100,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "response_time",
                    models.FloatField(
                        blank=True, help_text="Response time in seconds", null=True
                    ),
                ),
                (
                    "status_code",
                    models.IntegerField(default=200, help_text="HTTP status code"),
                ),
                (
                    "tokens_used",
                    models.IntegerField(
                        default=0, help_text="Approximate tokens used from API"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="chat_apiusa_user_id_a05c8c_idx",
                    )
                ],
            },
        ),
    ]
