# Generated by Django 5.2.8 on 2025-12-04 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_ratelimitconfig_apiusagelog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Tag name (e.g., 'Refraction', 'Business')",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#522888",
                        help_text="Hex color for the tag",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.AddField(
            model_name="chatsession",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags for organizing chats",
                related_name="sessions",
                to="chat.chattag",
            ),
        ),
    ]
